### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by Vatsalparsaniya** [Vatsalparsaniya/Data-Structure#1]
## Data-Structure
# Add Data-Structure Programs in any  Language

**Comment by ozmocode** [comment]
Hi, can i contribute? I'd like to add Javascript data-structure :)

**Comment by Vatsalparsaniya** [comment]
> 
> 
> Hi, can i contribute? I'd like to add Javascript data-structure :)

yes

**Comment by Navneet78** [comment]
hey can I do this for pyhton language.

**Comment by Vatsalparsaniya** [comment]
> 
> 
> hey can I do this for python language.

Ex: you want to add (stack.py) 
     follow procedure mention in README.md file
     add stack.py file in "stack" folder(if folder is not available then make)

**Comment by aansari4599** [comment]
hey i want to do this in Java

**Comment by vs666** [comment]
Hi,I want to do double ended queue and circular queue in java.

**Comment by pixel-z** [comment]
Hi, I want to do stacks in C

**Comment by Vatsalparsaniya** [comment]
> 
> 
> hey i want to do this in Java

You can.

**Comment by Vatsalparsaniya** [comment]
> 
> 
> Hi, I want to do stacks in C

yes, you can.

**Comment by Vatsalparsaniya** [comment]
> 
> 
> Hi,I want to do double ended queue and circular queue in java.

yes, you can...

**Comment by codelixir** [comment]
Hey! I'm fairly new to coding so I don't know much. But I would like to do a few problems in C. - 
1. Bubble Sort in Arrays
2. Reversing a Sentence (ex "Data structure program" outputs "program structure Data")
3. Something related to matrices

Can I do these?

**Comment by Vatsalparsaniya** [comment]
> 
> 
> Hey! I'm fairly new to coding so I don't know much. But I would like to do a few problems in C. -
> 
>     1. Bubble Sort in Arrays
> 
>     2. Reversing a Sentence (ex "Data structure program" outputs "program structure Data")
> 
>     3. Something related to matrices
> 
> 
> Can I do these?

yes

**Comment by Mayank-dev-commits** [comment]
Hi,I want to do single linked list in c language

**Comment by rajk1121** [comment]
@Vatsalparsaniya  Hi, I want to add linear search and binary search code in java.

**Comment by codelixir** [comment]
> > Hey! I'm fairly new to coding so I don't know much. But I would like to do a few problems in C. -
> > ```
> > 1. Bubble Sort in Arrays
> > 
> > 2. Reversing a Sentence (ex "Data structure program" outputs "program structure Data")
> > 
> > 3. Something related to matrices
> > ```
> > 
> > 
> > Can I do these?
> 
> yes

Thank You. Sent a pull request, kindly accept.

**Comment by stevhens** [comment]
hi @Vatsalparsaniya , I have implemented Single Linked List Program in Swift #79

**Comment by stevhens** [comment]
hi @Vatsalparsaniya , I have implemented Queue Program in Swift #89

**Comment by stevhens** [comment]
hi @Vatsalparsaniya , I have implemented Stack Program in Swift #95

**Comment by Murgowt** [comment]
Hey @Vatsalparsaniya  , Have implemented the Selection Sort Algorithm in python  #98

**Comment by ishitar** [comment]
Hi, @Vatsalparsaniya  have added singly linked list Java code. #113

**Comment by hieetesh** [comment]
Can I implement Circular Queue in JS ?

**Comment by rohitgeddam** [comment]
Hi I am first timer.
I want to contribute to your repository.
Where should i Start

**Comment by katariarajat** [comment]
hey! can i add programs like :
1)calculating factorial of a big number which cannot be stored in long long int.
2)inverse modulo with less time limit.
3)calculating smallest number with maximum number of set bits between two given numbers.

**Comment by yatip** [comment]
@Vatsalparsaniya  Hey, I want to contribute to this issue. I have checked therre is no selection sort in cpp. So can I add it?

**Comment by Utkarsh98** [comment]
Hi @Vatsalparsaniya I have added rat in a maze backtracking solution in C++.  #142

**Comment by hieetesh** [comment]
Hi @Vatsalparsaniya, I have added circular queue implementation in Java.

**Comment by raushan606** [comment]
Hi,  @Vatsalparsaniya, 
- Can I add bubble sort(ascending order) in python?
- Can I add polynomial addition in linked list in C++?
- Can I add swapping of two nodes in linked list in C++?
- Can I add 'removing of duplicate elements from unsorted linked list' ?

**Comment by saltgen** [comment]
Hello @Vatsalparsaniya I have added an optimized version of Quick Sort in Sorting folder, written in Python(quicksort.py).

Requesting your review [#149](https://github.com/Vatsalparsaniya/Data-Structure/pull/149)

**Comment by KrishnaPhalgun5168** [comment]
Hello @Vatsalparsaniya, Can I add XOR Linked List (Memory Efficient Doubly Linked List) in C++?
For more about XOR Linked List refer https://en.wikipedia.org/wiki/XOR_linked_list

**Comment by SEETHAMRAJU** [comment]
Can I add a piece of code for segment Trees?

**Comment by stevhens** [comment]
hi @Vatsalparsaniya, I have implemented Single Linked List Program in Swift #79  and Stack Program in swift #95 . 
Are there things I can do to make my pull requests reviewed?

**Comment by Vatsalparsaniya** [comment]
Don't worry i will review all pull requests

**Comment by shivambachhety** [comment]
Added tower of Hanoi problem in java 
https://github.com/shivambachhety/Data-Structure/pull/1

**Comment by moonpatroller** [comment]
Hi @Vatsalparsaniya  Please merge my pr

**Comment by Parag0506** [comment]
Hey can I contribute to the project?

**Comment by shubham10111** [comment]
Hey can I contribute to this project in python?

**Comment by Aveesh52** [comment]
Hey can I contribute to this project in python?

**Comment by Aveesh52** [comment]
Hey can I contribute to this project ?

**Comment by naman-sandilya** [comment]
Can i contribute to this project?

**Comment by darkdraiden14** [comment]
Nqueen in python #272
